### ISSUE TITLE
easy依赖了这个停止维护的库 com.zhy:okhttputils:2.6.2，找不到了

### ISSUE THREAD

**Issue by flymorn** [xuexiangjys/XUpdateAPI#3]
Could not find com.zhy:okhttputils:2.6.2.
Required by:
    project :app

看作者okhttp-utils的github：
由于个人原因，现已停止维护。5年前就停止维护了。

implementation 'com.github.xuexiangjys:XUpdate:2.0.9'
implementation 'com.github.xuexiangjys.XUpdateAPI:xupdate-easy:1.0.1'
implementation 'com.zhy:okhttputils:2.6.2'

**Comment by xuexiangjys** [comment]
不维护,但也不影响使用

**Comment by nikolamakin** [comment]
兄弟，你不维护，我这无法编译通过啊，以前1.0.0版本用的好好的，你既然升级就维护一下呗，这插件挺好用的，小星星送给你

Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.zhy:okhttputils:2.6.2.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/zhy/okhttputils/2.6.2/okhttputils-2.6.2.pom
  - https://repo.maven.apache.org/maven2/com/zhy/okhttputils/2.6.2/okhttputils-2.6.2.pom
  - https://jitpack.io/com/zhy/okhttputils/2.6.2/okhttputils-2.6.2.pom
Required by:
    project :app
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.zhy:okhttputils:2.6.2.

    project :app > com.github.xuexiangjys.XUpdateAPI:xupdate-easy:1.0.1

==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
17 actionable tasks: 7 executed, 10 up-to-date

**Comment by nikolamakin** [comment]
怎么解决这个问题呢，求告知，谢谢大佬

**Comment by xuexiangjys** [comment]
增加下面的仓库
jcenter { url 'https://maven.aliyun.com/repository/jcenter' }

**Comment by nikolamakin** [comment]
谢谢，解决了。
如果我们能有自己的仓库，岂不是美哉。嘿嘿

**Comment by LLAP-V** [comment]
jcenter也停止服务了，得改成 mavenCentral { url = uri('https://maven.aliyun.com/repository/jcenter' )}
